name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install jq (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y jq
      
    - name: Install jq (macOS)
      if: runner.os == 'macOS'
      run: brew install jq
      
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install jq -y
        echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH
      shell: bash
      
    - name: Check dependencies
      run: |
        bash --version
        jq --version
        curl --version | head -1
      shell: bash
        
    - name: Make scripts executable
      run: |
        chmod +x install.sh
        chmod +x tools/hello/world
        chmod +x tools/wiki/search
        chmod +x tests/*.sh
      shell: bash
        
    - name: Run test suite
      run: |
        chmod +x tests/run_ci.sh
        bash tests/run_ci.sh
      shell: bash
      
    - name: Test installer from GitHub
      run: |
        # Test that the installer can handle list mode
        # (may return empty list if API is unavailable)
        AGENT_MODE=1 bash ./install.sh --list | jq -e '.status == "success"'
      shell: bash
        
    - name: Test local installation
      run: |
        # Test actual installation
        # Use temp directory that works on all platforms
        TESTDIR="${RUNNER_TEMP:-/tmp}/test-install"
        mkdir -p "$TESTDIR"
        INSTALL_DIR="$TESTDIR" FORCE=1 bash ./install.sh hello.world
        
        # Verify installation
        test -f "$TESTDIR/hello.world"
        
        # Test the tool works (jq -e exits with 0 if true, 1 if false)
        echo '{"name":"CI"}' | "$TESTDIR/hello.world" | jq -e '.ok == true' > /dev/null
      shell: bash
        
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        ignore_paths: tests
        severity: error
        check_together: yes
        
  bash-compatibility:
    name: Bash Compatibility Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for Bash 4+ features
      run: |
        echo "Checking for associative arrays (Bash 4+ feature)..."
        # Check for actual declarations, not in comments or test files
        if grep -r '^[[:space:]]*declare[[:space:]]\+-A' . --include="*.sh" --exclude-dir=.git --exclude-dir=tests; then
          echo "ERROR: Found Bash 4+ associative arrays"
          exit 1
        else
          echo "✓ No associative arrays found"
        fi
        
        echo "Checking for mapfile (Bash 4+ feature)..."
        if grep -r '^[[:space:]]*mapfile' . --include="*.sh" --exclude-dir=.git --exclude="install.sh"; then
          echo "ERROR: Found Bash 4+ mapfile usage"
          exit 1
        else
          echo "✓ No mapfile usage found"
        fi
        
  documentation:
    name: Documentation Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check documentation files exist
      run: |
        for file in README.md LICENSE.md CLAUDE.md docs/api-contract.md docs/development.md docs/installation.md; do
          if [[ ! -f "$file" ]]; then
            echo "ERROR: Missing documentation file: $file"
            exit 1
          else
            echo "✓ Found: $file"
          fi
        done
        
    - name: Check tool documentation
      run: |
        for tool in tools/*/*; do
          if [[ -f "$tool" ]]; then
            echo "Checking $tool..."
            if ! $tool --help > /dev/null 2>&1; then
              echo "ERROR: $tool missing --help"
              exit 1
            fi
            if ! $tool --schema > /dev/null 2>&1; then
              echo "ERROR: $tool missing --schema"
              exit 1
            fi
          fi
        done
        echo "✓ All tools have documentation"